export const ENTRY_CONFIG = {
    DEFAULT_NEWS_ENTRY_HEIGHT: 270,
    DEFAULT_WORK_ENTRY_HEIGHT: 350,
    OPEN_NEWS_ENTRIES_BY_DEFAULT: 1,
    OPEN_WORK_ENTRIES_BY_DEFAULT: 3,
}

export const HATEOAS_INDEX = 'http://api.creative-coding.net/'