export const themes = {
    'default': {
        fontColor: '#000000',
        borderColor: '#336600',
        backgroundColorContent: '#FFFFFF',
        backgroundColorBody: '#333333',
        backgroundImageBody: '/background/default.svg',
        backgroundColorOuter: '#333333',
        transparentColor: 'transparent',
        gradientColorLight: '#427142',
        gradientColorDark: '#437243',
        hoverColor: '#EEEEEE',
        loadingColorLine: '#FFFFFF', //  '#931818',
        loadingColorBase: '#FFFFFF',
        loadingColorActive1: '#EEEEEE',
        loadingColorActive2: '#AAAAAA',
        loadingColorActive3: '#999999',
        loadingColorActive4: '#666666',
        loadingColorActiveText: '#666666',
        extraAccentColor: '#931818',
    },
    'crazy': {
        fontColor: '#8B5A1E',
        borderColor: '#FF1493',
        backgroundColorContent: '#00FFEE',
        backgroundColorBody: '#3B783A',
        backgroundImageBody: '/background/crazy.svg',
        backgroundColorOuter: '#333333',
        transparentColor: 'transparent',
        gradientColorLight: '#FF0000',
        gradientColorDark: '#FFFF00',
        hoverColor: '#00FFEE',
        loadingColorLine: '#00EDDD',
        loadingColorBase: '#00FFEE',
        loadingColorActive1: '#FF0000',
        loadingColorActive2: '#882828',
        loadingColorActive3: '#B12828',
        loadingColorActive4: '#C43838',
        loadingColorActiveText: '#FF4A15',
        extraAccentColor: '#E43BFF',
    }
}